name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/sample-react-app
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd ../../
          npm ci

      - name: Bootstrap generator & run tests
        run: |
          npx --no-install create-ai-e2e init
          npx --no-install create-ai-e2e scan src/ --json
          npx --no-install create-ai-e2e gen --ai
          
          # Start the development server in the background
          npm run dev &
          # Wait for the server to be ready
          npx wait-on http://localhost:5173
          
          # Run the tests with debug information
          npx playwright test --reporter=html --debug

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: examples/sample-react-app/playwright-report/
          retention-days: 30

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: examples/sample-react-app/test-results/
          retention-days: 30

#      - name: Ensure Playwright Report Directory Exists
#        run: mkdir -p examples/sample-react-app/playwright-report

#      - name: Upload Artifacts (optional)
#        uses: actions/upload-artifact@v3
#        with:
#          name: playwright-report
#          path: examples/sample-react-app/playwright-report
#
#  analyze-report:
#    needs: e2e
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: downloaded-report
#    steps:
#      - name: Download Playwright Report
#        uses: actions/download-artifact@v3
#        with:
#          name: playwright-report
#          path: .            # downloads into ./downloaded-report by default
#
#      - name: List report files
#        run: ls -R .