name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd examples/sample-react-app
          npm ci
          # Install Playwright browsers
          npx playwright install chromium

      - name: Build and run tests
        run: |
          cd examples/sample-react-app
          # Run the tests with Playwright's built-in server management
          npx playwright test --reporter=html

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: examples/sample-react-app/playwright-report/
          retention-days: 30
