name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: examples/sample-react-app
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: examples/sample-react-app/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('examples/sample-react-app/package-lock.json') }}

      - name: Authenticate with GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=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" > ~/.npmrc

      - name: Install create-ai-e2e globally
        run: npm install -g https://github.com/mikopos/create-ai-e2e

      - name: Install dependencies
        run: npm install

      - name: Bootstrap generator & run tests
        run: |
          npx create-ai-e2e init
          npx create-ai-e2e scan src/ --json
          npx create-ai-e2e gen --ai
          npx playwright test --reporter=html

#      - name: Ensure Playwright Report Directory Exists
#        run: mkdir -p examples/sample-react-app/playwright-report

#      - name: Upload Artifacts (optional)
#        uses: actions/upload-artifact@v3
#        with:
#          name: playwright-report
#          path: examples/sample-react-app/playwright-report
#
#  analyze-report:
#    needs: e2e
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: downloaded-report
#    steps:
#      - name: Download Playwright Report
#        uses: actions/download-artifact@v3
#        with:
#          name: playwright-report
#          path: .            # downloads into ./downloaded-report by default
#
#      - name: List report files
#        run: ls -R .